
CREATE TABLE GENRES (
  ID integer PRIMARY KEY,
  GENRE varchar(40)
);
CREATE TABLE COUNTRIES(
  ID integer PRIMARY KEY,
  COUNTRY varchar(30)
);

CREATE TABLE MOVIES (
  ID integer PRIMARY KEY NOT NULL,
  TITLE varchar(50),
  RELEASE_DATE INTEGER,
  GENRE integer NOT NULL,
  COUNTRY integer NOT NULL,
  PRICE integer,
  COVER varchar(240) NOT NULL,
  FOREIGN KEY (GENRE) REFERENCES GENRES(ID),
  FOREIGN KEY (COUNTRY) REFERENCES COUNTRIES(ID)
);
CREATE TABLE PERSON (
  ID integer PRIMARY KEY,
  NAME varchar(50),
  BIRTH_DATE DATE,
  PICTURE varchar(120) NOT NULL
);
CREATE TABLE MOVIEPERSON (
  ID integer PRIMARY KEY,
  MOVIE_ID integer,
  PERSON_ID integer,
  ISACTOR varchar(1),
  ISWRITER varchar(1),
  ISDIRECTOR varchar(1),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
  FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);
CREATE TABLE USERS (
  FIRST_NAME varchar(15),
  LAST_NAME varchar(15),
  EMAIL varchar(30) PRIMARY KEY NOT NULL,
  USERNAME varchar(50),
  PASSW varchar(20)
);
CREATE TABLE LIKES (
  MOVIE_ID integer,
  USER_EMAIL varchar(30),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
  FOREIGN KEY (USER_EMAIL) REFERENCES USERS(EMAIL)
);
CREATE TABLE COMMENTS (
  ID integer PRIMARY KEY,
  MOVIE_ID integer,
  USER_EMAIL varchar(30),
  TEXT varchar(100),
  COMMENT_DATE DATE DEFAULT CURRENT_DATE,
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
  FOREIGN KEY (USER_EMAIL) REFERENCES USERS(EMAIL)
);

INSERT INTO GENRES VALUES (1,'Akció');
INSERT INTO GENRES VALUES (2,'Dráma');
INSERT INTO GENRES VALUES (3,'Kaland');
INSERT INTO GENRES VALUES (4, 'Vígjáték');
INSERT INTO GENRES VALUES (5, 'Sci-fi');
INSERT INTO GENRES VALUES (6, 'Fantasy');
INSERT INTO GENRES VALUES (7, 'Animációs');
INSERT INTO GENRES VALUES (8, 'Dokumentum');

INSERT INTO COUNTRIES VALUES(1,'Amerika');

INSERT INTO MOVIES VALUES(1,'Harcosok klubja',1999,6,1,1000,'https://m.media-amazon.com/images/M/MV5BMjJmYTNkNmItYjYyZC00MGUxLWJhNWMtZDY4Nzc1MDAwMzU5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,676,1000_AL_.jpg');
